### ISSUE TITLE
Padding calculations for class boxes is unreasonably large

### ISSUE THREAD

**Issue by willkill07** [mucsci-students/2024sp-420-PythonB#225]
It should be a tight bounding-box fit.

<img width="683" alt="Screenshot 2024-04-04 at 8 58 20 AM" src="https://github.com/mucsci-students/2024sp-420-PythonB/assets/2007799/93150b89-7d09-4f14-be4f-346e249e190e">

**Comment by almostTaklu** [comment]
fixed.
